name: CI
on: [push, pull_request]

jobs:
  test-example:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/libextism
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm32-wasi-ghc (main)
        run: |
          git clone https://gitlab.haskell.org/ghc/ghc-wasm-meta
          pushd ghc-wasm-meta
          FLAVOUR=9.8 ./setup.sh

      - name: Build examples with tail-call support
        run: |
          source ~/.ghc-wasm/env
          make

      - name: Test with tail-call support
        run: |
          pushd test-host
          TEST=$(cargo run --release ../count_vowels.wasm count_vowels "this is a test")
          echo $TEST | grep '"count":4'
          TEST=$(cargo run ../hello.wasm testing "Name")
          echo $TEST | grep 'Hi there, Name'
      
      - name: Install wasm32-wasi-ghc (7a752b58)
        run: |
          pushd ghc-wasm-meta
          git reset --hard 7a752b58
          FLAVOUR=9.8 ./setup.sh
      
      - name: Build examples
        run: |
          source ~/.ghc-wasm/env
          make clean
          make

      - name: Test call command
        run: |
          TEST=$(extism call ./count_vowels.wasm count_vowels --wasi --input "this is a test")
          echo $TEST | grep '"count":4'

          TEST=$(extism call ./hello.wasm testing --wasi --input "Name" --config greeting="Hi there")
          echo $TEST | grep 'Hi there, Name'

          TEST=$(extism call ./http_get.wasm http_get --wasi --input "https://jsonplaceholder.typicode.com/todos/1" --allow-host '*.typicode.com')
          echo $TEST | grep '"userId": 1'
